---
title: "Minimal requirements for computer games"
author: "Luke Thompson"
date: "June 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(reshape2)
library(chron)

```

## Verdun

You can put some text here.

```{r verdun, fig.height=5, fig.width=9, dev='svg'}
verdun <- read.csv('verdun.csv')
verdun$time <- chron(times=verdun$time)
verdun <- melt(verdun, 
    id.vars=c('time', 'command'),
    variable.name='Measure',
    value.name='Percentage')

ggplot(verdun) +
    geom_line(aes(time, Percentage, col=Measure)) + 
    scale_x_chron(format = "%H:%M:%S", n = 5)
```


## Besiege

You can put some text here.

```{r besiege, fig.height=5, fig.width=9, dev='svg'}
besiege <- read.csv('besiege.csv')
besiege$time <- chron(times=besiege$time)
besiege <- melt(besiege, 
    id.vars=c('time', 'command'),
    variable.name='Measure',
    value.name='Percentage')

ggplot(besiege) +
    geom_line(aes(time, Percentage, col=Measure)) + 
    scale_x_chron(format = "%H:%M:%S", n = 5)
```
## csgo

You can put some text here.

```{r csgo, fig.height=5, fig.width=9, dev='svg'}
csgo <- read.csv('csgo.csv')
csgo$time <- chron(times=csgo$time)
csgo <- melt(csgo, 
    id.vars=c('time', 'command'),
    variable.name='Measure',
    value.name='Percentage')

ggplot(csgo) +
    geom_line(aes(time, Percentage, col=Measure)) + 
    scale_x_chron(format = "%H:%M:%S", n = 5)
```
## terraria

You can put some text here.

```{r terraria, fig.height=5, fig.width=9, dev='svg'}
terraria <- read.csv('terraria.csv')
terraria$time <- chron(times=terraria$time)
terraria <- melt(csgo, 
    id.vars=c('time', 'command'),
    variable.name='Measure',
    value.name='Percentage')

ggplot(terraria) +
    geom_line(aes(time, Percentage, col=Measure)) + 
    scale_x_chron(format = "%H:%M:%S", n = 5)
```

